const elements = {
  gold: document.getElementById('gold-display'),
  essence: document.getElementById('essence-display'),
  round: document.getElementById('round-display'),
  era: document.getElementById('era-display'),
  waveStatus: document.getElementById('wave-status'),
  waveInfo: document.getElementById('wave-info'),
  selectionInfo: document.getElementById('selection-info'),
  unitPanel: document.querySelector('.unit-panel'),
  commandGrid: document.getElementById('command-grid'),
  commandSlots: Array.from(document.querySelectorAll('.command-slot')),
  bossCountdown: document.getElementById('boss-countdown-display'),
  cameraOverlay: document.getElementById('camera-overlay'),
  lobbyOverlay: document.getElementById('scene-lobby'),
  settingsOverlay: document.getElementById('scene-settings'),
  playButton: document.getElementById('btn-play'),
  settingsButton: document.getElementById('btn-settings'),
  exitButton: document.getElementById('btn-exit'),
  settingsBackButton: document.getElementById('btn-settings-back'),
  settingsToLobbyButton: document.getElementById('btn-settings-to-lobby'),
  settingInterest: document.getElementById('setting-interest'),
  settingAutoFullscreen: document.getElementById('setting-auto-fullscreen'),
  settingSensitivity: document.getElementById('setting-sensitivity'),
  settingSensitivityValue: document.getElementById('setting-sensitivity-value'),
  settingPanSpeed: document.getElementById('setting-pan-speed'),
  settingPanSpeedValue: document.getElementById('setting-pan-speed-value'),
  dockyardUsage: document.getElementById('dockyard-usage'),
  gameOverOverlay: document.getElementById('scene-gameover'),
  gameOverTitle: document.getElementById('gameover-title'),
  gameOverMessage: document.getElementById('gameover-message'),
  gameOverStats: document.getElementById('gameover-stats'),
  gameOverRetry: document.getElementById('btn-gameover-retry'),
  gameOverLobby: document.getElementById('btn-gameover-lobby'),
  difficultyButtons: Array.from(document.querySelectorAll('[data-difficulty]')),
  difficultyLabel: document.getElementById('difficulty-label'),
  difficultySummary: document.getElementById('difficulty-summary'),
};

export { elements };
